### ISSUE TITLE
Teste para Desenvolvedor(a) Android - Sicredi

### ISSUE THREAD

**Issue by AlexandreHauber** [WoopSicredi/jobs#1]
Seja bem vindo! Obrigado pelo interesse em participar do nosso processo seletivo.

Leia atentamente as instruções abaixo e não hesite em entrar em contato com a gente :). 

## Objetivo

* Criar uma aplicativo que consuma uma REST API e exiba uma listagem de eventos;
* Cada item da lista deve permitir acesso à detalhes do evento;
* No detalhe do evento é importante exibir suas informações e opções de check-in e compartilhamento.

## Requisitos mínimos
* App deve compilar sem a necessidade de nenhum ajuste após ser clonado
* Suporte à API 19 e funcionar com a API mais recente do Android
* Código deve ser escrito em Kotlin
 
## Layout

A escolha do layout e disposição dos itens é livre.

## Sobre seu código

Analisaremos:

* Organização do código;
* Boas práticas de programação;
* Possíveis bugs;
* Tratamento de erros;
* O uso de frameworks e libraries é livre.

## API

A API de eventos está disponivel em:
https://5f5a8f24d44d640016169133.mockapi.io/api/events

Para acessar cada detalhe do evento basta adicionar o ID do item ao final da URL. Ex: https://5f5a8f24d44d640016169133.mockapi.io/api/events/1

Para realizar o check-in faça um POST no seguinte endereço: https://5f5a8f24d44d640016169133.mockapi.io/api/checkin
Ps: caso o check-in retorne a seguinte mensagem de erro "Max number of elements reached for this resource!", por favor entre em contato via e-mail avisando para corrigirmos o quanto antes.

O POST deve conter os dados do interessado (Nome, e-mail) e o id do evento. Ex:

`{
  "eventId": "1",
  "name": "Otávio",
  "email": "otavio_souza@..."
}`

## Itens extras

* Explicação breve  do porquê das escolhas de frameworks e arquitetura;
* Uso de testes unitários e de aceitação (interface).

## Dicas

* Dê atenção especial às recomendações do [Material Design](https://developer.android.com/design/material/index.html);
* Fique a vontade para utilizar animações e recursos especias (ex: parallax etc...);
* Teste bem seu aplicativo, evite crashes.
 
## Observações importantes

* Não inicie o teste sem sanar todas as dúvidas;
* A API pode ter falhas, prepare seu aplicativo para contorná-las.
* O aplicativo deve ser compartilhado através de um repositório **git**

### Bom teste!

**Comment by MGRies2** [comment]
É necessário armazenar os dados gerados pela API internamente? Ou pode ser feita uma requisição nova toda vez que for aberto o aplicativo?

**Comment by gustavoleite** [comment]
O post do checkin começou a retornar 400 depois de algumas requisições, parece que atingiu o limite do mock api.

<-- 400 Bad Request http://5b840ba5db24a100142dcd8c.mockapi.io/api/checkin (4095ms)
"Max number of elements reached for this resource!"

**Comment by heitor-gia** [comment]
> O post do checkin começou a retornar 400 depois de algumas requisições, parece que atingiu o limite do mock api.
> 
> <-- 400 Bad Request http://5b840ba5db24a100142dcd8c.mockapi.io/api/checkin (4095ms)
> "Max number of elements reached for this resource!"

Olá, boa tarde.
Estou com o mesmo problema de limite de requisições.

**Comment by fplimapereira** [comment]
https://github.com/fplimapereira/testeapi

**Comment by nataribeiro** [comment]
Bom dia, o post do checkin está retornando 400, mesmo problema relatado acima.

400 Bad Request
"Max number of elements reached for this resource!"

**Comment by arildojr7** [comment]
https://github.com/arildojr7/events-sample-android

**Comment by voumir** [comment]
Olá,
eu gostaria de usar a API mínima 21 (não a 19), **excepcionalmente** para este projeto que é em Kotlin.
Posso usar?

**Comment by brunotodeschini** [comment]
Olá, boa tarde.

Endpoint para check-in está retornando 400.
E exibindo a seguinte mensagem: "Max number of elements reached for this resource!"

Se não for possível reestabelecer a API, por favor adicionar um exemplo de retorno de sucesso e erro para o serviço. 

Obrigado.

**Comment by AlexandreHauber** [comment]
> Olá, boa tarde.
> 
> Endpoint para check-in está retornando 400.
> E exibindo a seguinte mensagem: "Max number of elements reached for this resource!"
> 
> Se não for possível reestabelecer a API, por favor adicionar um exemplo de retorno de sucesso e erro para o serviço.
> 
> Obrigado.

Bom dia!
Endpoint reestabelecido.
Att!

**Comment by fwgusberti** [comment]
Boa tarde, 

Endpoint para check-in está retornando 400 (Max number of elements reached for this resource!)

Poderia verificar?

**Comment by DaviPazzinis** [comment]
Olá,

O post do checkin começou a retornar "Max number of elements reached for this resource!"

Teria como restabelecer a api?

Obrigado! :)

**Comment by AlexandreHauber** [comment]
Bom dia!
Feito o ajuste.
Obrigado!

**Comment by DaviPazzinis** [comment]
https://github.com/DaviPazzinis/SicrediTeste

**Comment by xves** [comment]
https://github.com/xves/TestAndroid

**Comment by fabiioojr** [comment]
Boa tarde! Estou com o mesmo problema do pessoal na API

400 Bad Request
"Max number of elements reached for this resource!"

Poderia verificar?

**Comment by AlexandreHauber** [comment]
> Boa tarde! Estou com o mesmo problema do pessoal na API
> 
> 400 Bad Request
> "Max number of elements reached for this resource!"
> 
> Poderia verificar?

Ajustado 💪

**Comment by AlexandreHauber** [comment]
Foi necessário alterar os endpoints, já foram atualizados na descrição.
Caso encontrem algum problema, só avisar, por favor!

**Comment by ArthurLDS** [comment]
Boa tarde, tudo bem?

A API está com retornando erro **503 (Service Unavailable)**

Poderiam verificar?

**Comment by AlexandreHauber** [comment]
> Boa tarde, tudo bem?
> 
> A API está com retornando erro **503 (Service Unavailable)**
> 
> Poderiam verificar?

Opa, tudo bem? :)
Pode me informar qual está retornando 503, por favor? 

As apis mudaram na semana passada, são as novas que deram erro?

**Comment by ArthurLDS** [comment]
Era a API `http://5f5a8f24d44d640016169133.mockapi.io/api/`

Mas fiz mais uns testes agora, ela já voltou ao normal!

Obrigado :)

**Comment by AlexandreHauber** [comment]
Ah beleza, valeu!! :)

**Comment by ArthurLDS** [comment]
Segue a solução do teste 
https://github.com/ArthurLDS/app-events-sample-android

**Comment by JorgeDanilo** [comment]
@AlexandreHauber Boa noite, segue solução do teste abaixo:

https://github.com/JorgeDanilo/app-events-sicredi

**Comment by ForceTower** [comment]
Solução:  https://github.com/ForceTower/testing-events-app

**Comment by guitar09** [comment]
Olá, tudo beleza? 

a API de checkin-in está retornando o erro  Bad Request
"Max number of elements reached for this resource!"

poderia verificar por favor ?

**Comment by guitar09** [comment]
> Olá, tudo beleza?
> 
> a API de checkin-in está retornando o erro Bad Request
> "Max number of elements reached for this resource!"
> 
> poderia verificar por favor ?

Olá, voltou a funcionar Obrigado :)

**Comment by guitar09** [comment]
https://github.com/guitar09/app-events-test

**Comment by JuliaSantosMoura1201** [comment]
link do meu desafio https://github.com/JuliaSantosMoura1201/TestSicred

**Comment by AllexandreSantos** [comment]
Olá
Estou recebendo erro 503

**Comment by vn1miguel** [comment]
Boa noite! antes de começar, eu gostaria de saber se a API tem alguma documentação?

**Comment by vn1miguel** [comment]
Também encontrei erro: "Max number of elements reached for this resource!"

**Comment by vn1miguel** [comment]
Boa noite!
segue o link do teste: [SicrediEvent](https://github.com/vn1miguel/SicrediEvent)

**Comment by NewtonCesarRoncari** [comment]
Bom dia, 
segue o link do projeto teste: https://github.com/NewtonCesarRoncari/eventgo

**Comment by jotavier** [comment]
Boa tarde. A rota de check-in retorna a mensagem "Max number of elements reached for this resource!"

**Comment by jotavier** [comment]
Boa noite.
Segue link do meu projeto: https://github.com/jotavier/markup

**Comment by drirsousa** [comment]
https://github.com/drirsousa/woopsicred

**Comment by drirsousa** [comment]
Bom dia.
Segue o link do teste: https://github.com/drirsousa/woopevents

**Comment by clebernascimento** [comment]
Olá boa tarde!

O Endpoint de chekin está disabled.

![Capturar](https://user-images.githubusercontent.com/34046794/107695541-2447c480-6c87-11eb-8873-4a1d99c203ad.PNG)

// 20210211144829
// http://5f5a8f24d44d640016169133.mockapi.io/api/checkin

"Endpoint disabled"

**Comment by clebernascimento** [comment]
O Endpoint do checkin está dando not found

// 20210211180252
// http://5f5a8f24d44d640016169133.mockapi.io/api/chekin?checkin=1&name=teste&email=teste%40teste.com

"Not found"

Error 404

**Comment by marcotropeco** [comment]
Olá Boa noite,

Segue o link do meu teste : https://github.com/marcotropeco/EventsTest

Obrigado

**Comment by dricoldn** [comment]
Olá, boa tarde! Envio o link da minha avaliação https://github.com/dricoldn/AndroidIBM

**Comment by adelannucci** [comment]
Olá boa noite, 
Enviando os links para a  [Release v1.0.0](https://github.com/adelannucci/events/releases/tag/v1.0.0) e o  [Repository](https://github.com/adelannucci/events)

**Comment by vald3nir** [comment]
Bom dia, a chamada de check-in está retornando "Max number of elements reached for this resource!".

**Comment by gabriel-secchi** [comment]
Bom dia, Novamente a chamada do serviço de check-in está retornando "Max number of elements reached for this resource!".

**Comment by mborges18** [comment]
Olá, boa noite.
Aqui está o link do projeto: https://github.com/mborges18/eventos

**Comment by gillallifam** [comment]
https://github.com/gillallifam/SDTest1
Comentários na MainActivity.

**Comment by diegoleonds** [comment]
Bom dia, o checkIn (http://5f5a8f24d44d640016169133.mockapi.io/api/checkin) não está funcionando, apesar de retornar um 201

**Comment by marcosangelo** [comment]
Boa tarde, o checkin esta me retornando 503 - Service Unavailable. Obrigado.

**Comment by marcosangelo** [comment]
Agora mudou: "Max number of elements reached for this resource!" 400 - Bad Request

**Comment by rodrigopedro81** [comment]
Boa tarde, segue o link da minha avaliação :

https://github.com/rodrigopedro81/EventMate

**Comment by rmartorano** [comment]
Olá! O checkin está retornando "400 - Bad Request"

**Comment by JuliaSantosMoura1201** [comment]
Oi, estou recebendo 400 - Bad Request: "Max number of elements reached for this resource!"

**Comment by IgorCFG** [comment]
Tenho uma dúvida sobre o teste, no caso do item `people` no json, o padrão é não alterar a resposta de uma comunicação com API obviamente, porém, como é um teste, esse trecho `"people":[{"id":"1","eventId":"1","name":"name 1","picture":"picture 1"}` - "name 1", "picture 1" - poderia ser alterada por valores "reais" pra uma apresentação mais "bonita" do aplicativo?

**Comment by fagnerpo** [comment]
Teste Postado: https://github.com/fagnerpo/SiEventTest/tree/master

**Comment by lucaslaurodonato** [comment]
Segue teste : https://github.com/lucaslaurodonato/Avenue_code_test

**Comment by josimarmm01** [comment]
Bom dia, o POST do checkIn apesar de retornar "code: 200", não está funcionando.

**Comment by fernandozanutto** [comment]
Boa noite! Estou recebendo 400 - Bad Request: "Max number of elements reached for this resource!" no Post do checkin

**Comment by josimarmm01** [comment]
Bom dia segue o link do teste:
https://github.com/josimarmm01/TestSicredi

**Comment by fernandozanutto** [comment]
Boa tarde. Segue minha implementação:
https://github.com/fernandozanutto/ApiConnection

**Comment by tiagoivasco** [comment]
Bom dia!
estou recebendo code 400 no checkin

**Comment by Carlosjr01** [comment]
Bom dia. 
https://github.com/Carlosjr01/Events

**Comment by Lucas-diniz** [comment]
Bom dia, o post do check-in está retornando 400, mesmo problema relatado acima.
"Max number of elements reached for this resource!"

**Comment by erissonbcs** [comment]
Olá, segue o teste.
https://github.com/erissonbcs/TextGx2Sicredi

**Comment by MatheusHenAlmeida** [comment]
Boa noite, o post do check-in está retornando 400, mesmo problema relatado acima.
"Max number of elements reached for this resource!"
