### ISSUE TITLE
Teste para QA da Plataforma Digital Sicredi

### ISSUE THREAD

**Issue by leoduprates** [WoopSicredi/jobs#2]
**Seja bem vindo**! Obrigado pelo interesse em participar do nosso processo seletivo.

Leia atentamente as instruções abaixo e não hesite em entrar em contato com a gente :).

### Qual o objetivo?

**Negócio**
- Analise a história e defina os testes de aceitação.
- Exponha o planejamento para execução dos testes.
- Informe e justifique as técnicas de testes escolhidas.

**Técnico**
- Desenvolver projeto de testes automatizados para testes de UI e Serviços.
- Escolha a tecnologia e o framework de automação de testes de sua preferência.
- Limite a quantidade de testes automatizados e foque na qualidade da solução.

### O que será avaliado?
- Analise, planejamento e técnicas de teste.
- Mapeamento de cenários de testes.
- Orientação a objetos.
- Estrutura dos testes automatizados (Preparação, Execução e Validação).
- Arquitetura do projeto de automação (PageObjects, Features, Step Definitions, Datapool, Dataprovider, Framework).
- Boas práticas de desenvolvimento de software (design pattern, clean code e etc).
- Simplicidade e objetividade.

### Teste

**Chegou a hora de poupar!**  Mas quanto? Em quanto tempo? Como posso saber?

Nosso associado gostaria de simular o investimento na poupança para descobrir qual o valor ideal e quanto ele vai poupar no prazo que escolher.

Vamos construir um simulador de investimentos?

#### História

**Com o propósito de** Simular um Investimento na Poupança
**como um** Associado,
**eu gostaria de** preencher o formulário de simulação
**e ver** a tabela de resultado com Mês e Valor.

**Critério de aceitação:**
1. O associado preencher todos os campos corretamente e visualizar o formulário de simulação
2. O associado preencher o valor inferior a “R$ 20.00” e receber a mensagem de orientação “Valor mínimo de R$ 20.00”.

**Url:** https://www.sicredi.com.br/html/ferramenta/simulador-investimento-poupanca/

#### API:

A API do Simulador de Investimento está disponível em:

**Get:**
Url: http://5b847b30db24a100142dce1b.mockapi.io/api/v1/simulador

**Response:**
```json
{
    "id": 1,
    "meses": ["112", "124", "136", "148"],
    "valor": ["2.802", "3.174", "3.564", "3.971"]
}
```

### Entrega

Crie um repositório de versionamento para seus arquivos, tal como Git, e nos envie somente a URL. **Não aceitaremos** entregas de outras maneiras.

**Bom teste!**

**Comment by rosangelasegatto** [comment]
[Digital_Cenarios_v1.txt](https://github.com/WoopSicredi/jobs/files/2442488/Digital_Cenarios_v1.txt)

**Comment by rosangelasegatto** [comment]
[woopSicredi.zip](https://github.com/WoopSicredi/jobs/files/2442502/woopSicredi.zip)

**Comment by rosangelasegatto** [comment]
Get: Url: http://5b847b30db24a100142dce1b.mockapi.io/api/v1/simulador

Ferramenta utilizada Postman:
![postman_response](https://user-images.githubusercontent.com/37224013/46492518-290d2b80-c7e4-11e8-89be-1d450ca9760f.jpg)
![postman_response_preview](https://user-images.githubusercontent.com/37224013/46492520-290d2b80-c7e4-11e8-82a6-0d9e4f1d94b4.jpg)

**Comment by rosangelasegatto** [comment]
Informe e justifique as técnicas de testes escolhidas:
- Foi utilizado o BDD para os critérios de aceitação, a fim de melhorar a especificações através de exemplos.
- Automatizados os critérios de aceitação informados:
   Simulação com sucesso e com valor minimo não atingido.
- Para testes de serviços foi utilizada a ferramenta Postman.

**Comment by eduardo-gastal** [comment]
Prezados, segue em anexo a prova técnica.
Eduardo Carvalho Gastal.
[prova técnica Zallpy Eduardo Carvalho Gastal.docx](https://github.com/WoopSicredi/jobs/files/2654462/prova.tecnica.Zallpy.Eduardo.Carvalho.Gastal.docx)

**Comment by Sandrini** [comment]
Boa tarde,

Segue anexo a parte técnica e de negócio.

Obrigado pela atenção!
Sandrini Brum Peixoto.


[SimuladorSicredi.zip](https://github.com/WoopSicredi/jobs/files/2664886/SimuladorSicredi.zip)
[Cenários de Aceite Funcionalidade Simulador de Investimentos - Teste Sicredi.pdf](https://github.com/WoopSicredi/jobs/files/2664889/Cenarios.de.Aceite.Funcionalidade.Simulador.de.Investimentos.-.Teste.Sicredi.pdf)

**Comment by Sandrini** [comment]
Boa tarde,

Só para informar, quando simulamos um investimento para um único mês, a mensagem na tela do resultado aparece com um erro ortográfico: "Em 1 meses você terá guardado", quando deveria ser "Em 1 mês você terá guardado".

Atenciosamente,
Sandrini Brum Peixoto.

**Comment by Sandrini** [comment]
Retificando, um erro de concordância verbal.
![image](https://user-images.githubusercontent.com/5169981/49760919-c5542280-fcac-11e8-8d7e-1b2f816956d5.png)

Atenciosamente,
Sandrini Brum Peixoto

**Comment by kilaG** [comment]
Segue teste em anexo.
[Sicredi.zip](https://github.com/WoopSicredi/jobs/files/2852322/Sicredi.zip)
[TestAutomation.zip](https://github.com/WoopSicredi/jobs/files/2852323/TestAutomation.zip)

Att

Guilherme Kila

**Comment by helinhares** [comment]
Segue o teste realizado.
[Teste Henrique.zip](https://github.com/WoopSicredi/jobs/files/2877728/Teste.Henrique.zip)
