### ISSUE TITLE
Teste para Desenvolvedor(a) iOS do Woop Sicredi

### ISSUE THREAD

**Issue by delfinoae** [WoopSicredi/jobs#3]
Seja bem vindo! Obrigado pelo interesse em participar do nosso processo seletivo.

Leia atentamente as instruções abaixo e não hesite em entrar em contato com a gente :)

## Objetivo

* Criar um aplicativo em Swift que consuma uma REST API e exiba uma listagem de eventos
* Cada item da lista deve permitir acesso à detalhes do evento
* No detalhe do evento é importante exibir suas informações e opções de check-in e compartilhamento

## Sobre seu código

Analisaremos:

* Organização do código
* Boas práticas de programação
* Possíveis bugs
* Tratamento de erros
* O uso de frameworks e libraries é livre
* Uso de testes unitários
* AutoLayout

Diferencial:

* Usar RxSwift
* MVVM

## API

A API de eventos está disponivel em:
http://5b840ba5db24a100142dcd8c.mockapi.io/api/events

Para acessar cada detalhe do evento basta adicionar o ID do item ao final da URL. Ex: http://5b840ba5db24a100142dcd8c.mockapi.io/api/events/1

Para realizar o check-in faça um POST no seguinte endereço: http://5b840ba5db24a100142dcd8c.mockapi.io/api/checkin

O POST deve conter os dados do interessado (Nome, e-mail) e o id do evento. Ex:

`{
  "eventId": "1",
  "name": "Otávio",
  "email": "otavio_souza@..."
}`

## Dicas

* Faça commits frequentes. Queremos entender como você pensa :)
* Fique a vontade para utilizar animações e recursos especias (ex: parallax etc...)
* Teste bem seu aplicativo, evite crashes
 
## Observações importantes

* Fique à vontade para tirar dúvidas em qualquer etapa do processo
* A API pode ter falhas, prepare seu aplicativo para contorná-las
* Crie um repositório e compartilhe conosco para avaliarmos o seu código

**Comment by EduardoSeguraFornari** [comment]
Bom dia Allan, segue o link do repositório com a minha solução para o teste.

https://github.com/EduardoSeguraFornari/Events

**Comment by rodrigowoulddo** [comment]
Olá! 😁
O endpoint `/checkin` está retornando um `400 Bad Request`.
A descrição do erro é `Max number of elements reached for this resource!`.

**Comment by AlexandreHauber** [comment]
Foi necessário alterar os endpoints, já foram atualizados na descrição.
Caso encontrem algum problema, só avisar, por favor!

**Comment by dedeexe** [comment]
O endpoint 
http://5f5a8f24d44d640016169133.mockapi.io/api/events/1
está retornando strings em longitude e latitude, diferente dos demais elementos que retorna um valor flutuante,

**Comment by AlexandreHauber** [comment]
> O endpoint
> http://5f5a8f24d44d640016169133.mockapi.io/api/events/1
> está retornando strings em longitude e latitude, diferente dos demais elementos que retorna um valor flutuante,

Corrigido, obrigado pelo aviso!

**Comment by dedeexe** [comment]
As datas nos endpoints são valores inteiros, porém o timestamp calculado não bate com o esperado. Está gerando datas muito longe da expectativa de vida humana :D, então talvez uma das alternativas:
- As datas estão corretas e são de eventos para as gerações futuras
- Os timestamps estão vindo com valor multiplicado por 1000 por talvez possuirem precisão milesimal mas por algum motivo vem representados em inteiro e eu precisaria fazer os cálculos necessários do lado do client(o que seria um pouco esquisito)
- Datas devessem vir em string.
Qual seria o corruto entre as opções, ou então qual seria a alternativa à elas.

**Comment by ndrsKloss** [comment]
@dedeexe os valores do campo date estão em milissegundo, o que esta errado, epoch time é em segundos. Vamos arrumar. E datas em epoch são representadas em inteiro mesmo.

**Comment by luizfetrindade** [comment]
Olá, estou também tendo o mesmo retorno:
status 400 para o checkin
com Max number of elements reached for this resource!.

**Comment by AlexandreHauber** [comment]
> Olá, estou também tendo o mesmo retorno:
> status 400 para o checkin
> com Max number of elements reached for this resource!.

Ajustado! (y)

**Comment by rodrigomarcelino** [comment]
O endpoint http://5f5a8f24d44d640016169133.mockapi.io/api/checkin está desabilitado

**Comment by vcsoares** [comment]
O endpoint de Checkin está retornando status 400 aqui também, com a mesma mensagem de "Max number of elements reached for this resource!".

**Comment by lfernandosantos** [comment]
Está retornando status 400 com a mensagem de "Max number of elements reached for this resource!", para o checkin.

**Comment by lfpolo** [comment]
O endpoint do checkin está desabilitado
[(http://5f5a8f24d44d640016169133.mockapi.io/api/checkin)]

**Comment by renanmd** [comment]
Bom dia! A propriedade "people" : [], esta vazia. O que seria retornado dentro do array? Teria um retorno de examplo?

Outra, não seria mais recomendado a url ser HTTPS?

**Comment by ritacvn** [comment]
Olá, o endpoint do checkin está desabilitado

**Comment by Joao-LDS** [comment]
O checkin está desabilitado.

**Comment by josiasfabricio** [comment]
Olá, o endpoint do checkin está offline.

**Comment by juniorobici** [comment]
Olá,
O checkin está retornando status 400
"Max number of elements reached for this resource!"
