### ISSUE TITLE
Teste Analista de Negócios Transformação Digital Sicredi

### ISSUE THREAD

**Issue by bamp** [WoopSicredi/jobs#5]
Seja bem vindo! Obrigado pelo interesse em participar do nosso processo seletivo.

Leia atentamente as instruções abaixo e não hesite em entrar em contato com a gente :)

**Objetivo**
Simular o planejamento de uma sprint de produto. 

Você está iniciando um novo trabalho em um site de e-commerce e precisa organizar a sprint da sua squad considerando um backlog herdado de um trabalho que o time já vinha realizando.  

*Alguns pontos sobre a forma de trabalho:* 

•	As sprints são de duas semanas;
•	A velocidade do time é de 12 story points por sprint;
•	Quando a sprint estiver finalizada ela deverá entregar valor para o usuário;
•      O ID corresponde ao código da história, não é uma ordem de prioridade.

**Product Backlog**

| Backlog ID |   Como  | Eu desejo... | Para que... | Obs. |  Story points |
| :------------ | :------------ |:---------------:| -----:| -----:| -----:|
|1 | Cliente | poder encontrar produtos   que desejo adquirir baseado em sua categoria | eu possa incluir   no carrinho de compras |   | 3
|2 | Cliente | poder encontrar   produtos que desejo adquirir baseado em palavras-chave | eu possa incluir   no carrinho de compras |   | 3
|3 | Cliente | desejo poder ver detalhes   do produto selecionado | eu tenha   informações detalhadas do produto |   | 5|
|4 | Cliente | desejo poder   incluir produto selecionado no carrinho | eu possa ter   vários produtos dentro do carrinho | Sem cálculo de   frete | 3|
|5 | Cliente | desejo finalizar   a compra utilizando cartão de crédito de uma operadora | que possa comprar   os produtos em meu carrinho |   | 8
|6 | Cliente | desejo finalizar   a compra utilizando o cartão de crédito de uma operadora adicional | que possa comprar   os produtos em meu carrinho |   | 8
| 7 | Gerente de Logística | desejo poder   acompanhar o despacho e logística das compras através da integração com o   sistema da empresa XX | meu cliente possa   acompanhar a entrega de suas compras |   | 21|
|8 | Cliente | desejo usar meu   e-mail e senha | eu possa me logar   no site |   | 1|
9 | Cliente | desejo usar minha   conta do Facebook | eu possa me logar   no site |   | 3|
10 | Desenvolvedor | desejo poder   autenticar-me em um site via autenticação do Facebook | eu possa   compreender superficialmente as dificuladades técnicas desta integração |   | 8|

**Pontos de Avaliação**
•	A forma como você organizou a sprint;
•	Capacidade de avaliar complexidade das histórias;
•	Embasamento da priorização;
•	Avaliação/Gestão do backlog;
•	Capacidade de identificar oportunidades e propor melhorias.

**Comment by samuellopesf** [comment]
Pessoal, tudo bem? Espero que sim!

Em anexo, segue sprint.

Abraço e obrigado pela oportunidade!
[Apresentação Desafio - Samuel Lopes Feldmann.pdf](https://github.com/WoopSicredi/jobs/files/2368661/Apresentacao.Desafio.-.Samuel.Lopes.Feldmann.pdf)
[Apresentação Desafio.pptx](https://github.com/WoopSicredi/jobs/files/2368663/Apresentacao.Desafio.pptx)
