### ISSUE TITLE
Teste para Desenvolvedor(a) Web Sicredi

### ISSUE THREAD

**Issue by Lucas-Inhaquite** [WoopSicredi/jobs#6]
Seja bem vindo! Obrigado pelo interesse em participar do nosso processo seletivo.

Leia atentamente as instruções abaixo e não hesite em entrar em contato com a gente :).

## Objetivo

**Criar uma aplicação que contenha​:**

Página de login:
   * Única página disponível se não estiver logado;
   * Criar um usuário básico para acesso.

Uma página de lista de dragões:
   * Os nomes devem estar em ordem alfabética;
   * A partir da lista, deverá ser possível remover e alterar as informações dos dragões.

Uma página com os detalhes de um dragão específico:

 Os seguintes dados devem ser apresentados na página:
   * Data de criação;
   * Nome;
   * Tipo.

Uma página para cadastro de dragões:

**Regras:**

* Layout responsivo;
* Utilizar Stencil, React, Angular 6+ ou Web Components;
* Usar um sistema de controle de versão para entregar o teste (Github, Bitbucket, ...).

**O que será avaliado:**
* Organização do código;
* Componentização das páginas;
* Interface organizada e amigável;
* Uso adequado do css/sass/less. NÃO é permitido usar bibliotecas de estilos como: bootstrap, material design, etc.

## API
`http://5c4b2a47aa8ee500142b4887.mockapi.io/api/v1/dragon`
#### GET `.../api/v1/dragon`
lista de dragões

#### GET `.../api/v1/dragon/:id`
detalhes de um draão

#### POST `.../api/v1/dragon`
criação de um dragão

#### PUT `.../api/v1/dragon/:id` 
edição de um dragão

#### DELETE `.../api/v1/dragon/:id`
deleção de um dragão

## Bom teste!

**Comment by amarildo91** [comment]
Olá,
segue o repositório para acesso.

[https://github.com/amarildo91/dragon-project](url)

**Comment by gabrielmf** [comment]
Olá, aqui está meu repositório, qualquer dúvida é só entrar em contato.

https://github.com/gabrielmf/dnd-app

**Comment by Eds-FrontEnd** [comment]
Olá! Segue o projeto do desafio Dragões - vaga Desenvolvedor Front End:
 https://github.com/Eds-FrontEnd/DragonsApp

**Comment by gianmachado** [comment]
Dragon Sicredi - Challenge
Link: [GITHUB](https://github.com/gianmachado/dragon-sicredi)

Method to sign in application is described into README.md

**Comment by maycklima** [comment]
Desafio Proposto: Dragões Sicred

Link:
<a href=“[https://github.com/maycklima/sicred-dragon](http://flexgridframework.com/)“>Github</a>

**Comment by maycklima** [comment]
Desafio Proposto: Dragões Sicred

Link da Resolução:
<a href="https://github.com/maycklima/sicred-dragon">GitHub</a>

**Comment by GuilhermeOlavoLaux** [comment]
Desafio Proposto: Dragões Sicredi

Link da Resolução: https://github.com/GuilhermeOlavoLaux/dragons
Usuário para acessar a aplicação: Teste
Senha: 123

**Comment by dancastelo** [comment]
Desafio Proposto: Dragões Sicred

Link da Resolução:
[GitHub](https://github.com/dancastelo/sicred-dragoes)

**Comment by leomayca** [comment]
Desafio: Sicredi Dragons

Resolução: https://github.com/leomayca/sicred-dragons-form

**Comment by JoaoVictorCabraldeMelo** [comment]
Desafio: Sicredi Dragons

[Resolucao](https://github.com/JoaoVictorCabraldeMelo/dragon-api)

**Comment by Gabb-c** [comment]
## WoopSicredi Dragon Challenge

Repository - https://github.com/Gabb-c/woop-dragon
Deploy - https://woop-dragon.vercel.app

```
Username: woop@sicredi.com.br
Password: SuperSecretPassword
```

More details in project [README.md](https://github.com/Gabb-c/woop-dragon#readme)

**Comment by Andreywrl** [comment]
## Sicredi - Developer Challenge
Project content: <a href="https://github.com/Andreywrl/cwi-challenge" target="_blank">Click here.</a>
Project description (PT-BR): <a href="https://github.com/Andreywrl/cwi-challenge/blob/master/README.md" target="_blank">Click here.</a>
Deploy: <a href="https://cwi-challenge.vercel.app/" target="_blank">Click here.</a>

### Tester credentials:
User: **tester**
Password: **@t35t3r10**
